---
title: "An Example Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\Vign etteIndexEntry{An Example Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(bis557)
library(palmerpenguins)
library(DT)
data(penguins)
datatable(penguins)
```

Above is the `penguins` data set from the {palmerpenguins} package.


```{r}
library(dplyr)
library(ggplot2)
```

```{r}
#The tidy way
penguins %>% 
  select(species, island) %>% 
  table

#The base way
table(penguins$species, penguins$island)
```

## Filtering rows

# "base" way
```{r}
table(penguins[penguins$species=="Adelie","sex"])
```

# "tidy" way
```{r}
penguins %>% 
  filter(species=="Adelie") %>% 
  select(sex) %>% 
  table()
```

# Building a model

Let's fit the model: 

$$
\text{bill_length_mm} \sim \text{species} \, \beta_1 + \text{island} \, \beta_2 + \text{sex} \, \beta_3 + \beta_0
$$
To fit the model we'll run the following code: 

```{r}
fit<-lm(bill_length_mm~species + island+sex, data=penguins)
summary(fit)
qqnorm(fit$residuals)
```

# Plot residuals


```{r}
#base
qs<-qqnorm(fit$residuals, plot.it=F)
qsd<-as.data.frame(qs)
ggplot(qsd, aes(x=x, y=y)) + 
  geom_point() + 
  ylab("Sample Quantiles") + 
  xlab("Theoretical Quantiles") + 
  theme_minimal()
```

```{r}
qqnorm(fit$residuals, plot.it=F) %>% 
  as_tibble() %>% 
  ggplot(aes(x=x, y=y)) + 
  geom_point() + 
  ylab("Sample Quantiles") + 
  xlab("Theoretical Quantiles") + 
  theme_minimal()
```

